USE_CUDNN := 1
OPENCV_VERSION := 3
BLAS := atlas
ANACONDA_HOME := /opt/conda
PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
		 $(ANACONDA_HOME)/include/python3.5m \
		 $(ANACONDA_HOME)/lib/python3.5/site-packages/numpy/core/include
PYTHON_LIB := $(ANACONDA_HOME)/lib
PYTHON_LIBRARIES := boost_python3 python3.5m
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include /usr/include/hdf5/serial/
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib
CUDA_DIR := /usr/local/cuda-7.5
WITH_PYTHON_LAYER := 1
BUILD_DIR := build
DISTRIBUTE_DIR := distribute
TEST_GPUID := 0
CUDA_ARCH := -gencode arch=compute_52,code=sm_52 \
		-gencode arch=compute_52,code=compute_52
Q ?= @
